name: Flask CI Workflow

on:
  workflow_dispatch:

env:
  APP_DIR: 03-Actions/project-files
  
jobs:
  flask-ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t cwwj-flask-app:v1.0.0 -f $APP_DIR/Dockerfile $APP_DIR

      - name: Run Container
        run: |
          docker run -d -p 5000:5000 --name cwwj-flask-container cwwj-flask-app:v1.0.0

      - name: Smoke Test
        run: |
          sleep 5
          curl http://localhost:5000/health
